# Site settings
title:          Pie's Blog
description:    "My blog"
baseurl:        "/blog"
url:            "https://pie001.github.io"

# Author
author:
  name:         pie
  url:          https://chester.how
#  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
